### ISSUE TITLE
auto connect at the beginning

### ISSUE THREAD

**Issue by juanjoabarca** [taylanyildiz/MQTT-Provider-Listenable-Message#1]
I am developing a flutter application and I have taken your code as a guide, I wanted to ask you for help, I need the connectMqtt() method to be called automatically when starting the app and to establish a connection without pressing buttons.
I hope I can count on your help, thanks.

**Comment by taylanyildiz** [comment]
Hey, @juanjoabarca  I wrote this code on stackoverflow for you.
here : [MQTT](https://stackoverflow.com/a/71595051/16820776)

you will just run the initialize command to be able to connect and be careful for your mqtt host address if you run in local host get ip address  from comand line `ipconfig` 

If you still don't understand, you can write me.
